export const ADD_TODO = "ADD_TODO";

export const SEARCH_TODO = "SEARCH_TODO";

export const UPDATE_TODO = "UPDATE_TODO" //remaining

// export const SLELECT_COMPLETE = "SLELECT_COMPLETE";
// export const SLELECT_INCOMPLETE = "SLELECT_INCOMPLETE";
// export const SLELECT_ALL = "SLELECT_ALL";

export const FILTER_TODO = "FILTER_TODO"

export const TOGGLE_TODO = "TOGGLE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLETE_TODO = "MARK_COMPLETE_TODO";
export const MARK_INCOMPLETE_TODO = "MARK_INCOMPLETE_TODO";

export const MARK_COMPLETE_ALL_TODO = "MARK_COMPLETE_ALL_TODO";